### ISSUE TITLE
Ready for usage?

### ISSUE THREAD

**Issue by yazd** [vnayar/s2geometry-d#1]
Hello and thanks for your work on this.

Is the project in its current state ready for usage? Are there any important missing features or things that exist in s2 but not available here yet?

**Comment by vnayar** [comment]
There's a large batch of changes related to the utility class "S2Builder"
and the geometrical logic in "S2Polygon".  Those I'm working on in a
separate branch and I'm hoping to merge them in soon.  However, if all you
are using are basic shapes, loops, etc. then it should be ready.  The
"S2Buidler" class has a lot more complicated logic for taking care of noisy
data and turning it into clean Polygon boundaries.

 - Vijay

**Comment by yazd** [comment]
That's great.
Thanks!

On a side note, it would be nice to get updated releases on dub containing the latest changes, as the current version on dub doesn't even build.

**Comment by vnayar** [comment]
Will do.  Life has just gotten unexpectedly busy in the past several
months, but making progress on this project (albeit slow) keeps me sane.

By the way, what version of DMD were you using and what kinds of errors
were you getting with the current release version?  Unfortunately the
library makes heavy use of randomized values in tests, meaning that it's
indeed possible that you encountered an error that I did not.  Also, I
think it's possible that certain features I was using have now become
deprecated.

 - Vijay

**Comment by yazd** [comment]
I tried v0.0.1 a few days ago using dmd v2.082.0 and there were, IIRC, imports missing for S2PointIndex or some related module, but I am currently using ~master and things are going good. The problems were compile-time, not run-time.

I think I can reproduce the problems if you are interested to know more, but using master is going good.

**Comment by vnayar** [comment]
Ok that's great!  I'm hoping to have the rest of the goodies soon.  The was
a network of circular dependencies between S2Builder, S2BooleanOperation,
S2Polygon, S2BuilderGraph, SnapFunction, and a bunch of other things as
well.  But the biggest and hardest bugs have been worked out with the aid
of excessive print statements :P  I anticipate around a month before 100%
feature compatibility with the C++ version is established.

Though there's quite a bit of logic already.  My first exposure to the S2
Geometry library was with the Java port, and that port only had a tiny
fraction of the total features.  But you can do amazing things with S2Cap,
S2Cells, etc.  I was using it to turn geographical search radius into a set
of around 8 S2Cells of varying sizes, and these cell IDs were used to index
drivers.  Then when a customer was searching for drivers, finding them by
radius could be done in the blink of an eye.

Happy coding,

 - Vijay

**Comment by vnayar** [comment]
I just wrapped up fixing what I think are the last remaining bugs in S2Polygon this morning.  There's some clean-up that needs to be done, but this library is just about complete.  Outside of C++, I don't think any other programming language has full feature support like this.

**Comment by vnayar** [comment]
A release will be coming in the coming week.

**Comment by vnayar** [comment]
Release v0.2 is now ready for use.

**Comment by denizzzka** [comment]
Do not want to open a separate ticket, my the question correlates with the previous one.

What situation with implementation of Encode/Decode? Currently it commented out.

**Comment by vnayar** [comment]
At the moment it is not done, and I did not plan on completing that part
unless a use-case arrived.  Right now I'm deciding between starting my
original project that I wanted to use S2Geometry for, vs. adding any
remaining features not currently present.  Could you say a bit more about
your use-case and the expected value this feature would bring?

 - Vijay

**Comment by denizzzka** [comment]
I just want to play with OSM data loaded into s2geometry.
My previous experiments (with my own r-tree storage) showed to me what loading and indexing is very time-consuming process. It will be useful to save data from s2geometry storage into file after indexing process is done and reuse it.

**Comment by vnayar** [comment]
That does sound pretty darn useful.  Ok, I'll start this work this weekend,
but it probably won't be complete for all the S2 objects for a month or so.

**Comment by denizzzka** [comment]
Спасибо, это было бы очень здорово! Может я чем-то смогу помочь? (Я не смотрел глубоко внутрь)

**Comment by vnayar** [comment]
I have encode/decode implemented for all S2Region classes, but the encoding/decoding of the index itself was not actually even in the original C++ code I ported from, and I have no plans on adding it myself (I have other projects I need to focus on).
